language: go
go: 1.10.2
install: 
  - go get github.com/magefile/mage
  - mage -v vendor
script: mage -v ci
after_success:
  - test -n "$TRAVIS_TAG" && curl -sL http://git.io/goreleaser | bash
notifications:
  email: false
